POST http://localhost:3000/users/
Content-Type: application/json

{
    "username": "Zad2000",
    "password": "zad_2000"
}

###

POST http://localhost:3000/login/
Content-Type: application/json

{
    "username": "Gad2000",
    "password": "gad_2000"
}

###

POST http://localhost:3000/tasks/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdhZDIwMDAiLCJpYXQiOjE3MTQ1NjY4MTJ9.xtrLfOSr1fZ0Cq1ZyW88pNvaPJsKe4VcZw1bncdWbYM

{
    "title": "Java assignment",
    "description": "Complete the JAVA assignment",
    "status": "INCOMPLETE",
    "assigneeId": 3
}

###

GET http://localhost:3000/tasks/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdhZDIwMDAiLCJpYXQiOjE3MTQ1NjY4MTJ9.xtrLfOSr1fZ0Cq1ZyW88pNvaPJsKe4VcZw1bncdWbYM

###

GET http://localhost:3000/tasks/9/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdhZDIwMDAiLCJpYXQiOjE3MTQ1NjY4MTJ9.xtrLfOSr1fZ0Cq1ZyW88pNvaPJsKe4VcZw1bncdWbYM

###

PUT http://localhost:3000/tasks/9/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdhZDIwMDAiLCJpYXQiOjE3MTQ1NjY4MTJ9.xtrLfOSr1fZ0Cq1ZyW88pNvaPJsKe4VcZw1bncdWbYM

{
    "title": "C assignment",
    "description": "Complete the C assignment",
    "status": "INCOMPLETE"
}

###

DELETE http://localhost:3000/tasks/11/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdhZDIwMDAiLCJpYXQiOjE3MTQ1NjY4MTJ9.xtrLfOSr1fZ0Cq1ZyW88pNvaPJsKe4VcZw1bncdWbYM

###